services:
  nanobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nanobot
    volumes:
      - nanobot-workspace:/root/.nanobot/workspace
    restart: unless-stopped
    # default dari Dockerfile kamu: ENTRYPOINT ["nanobot"], CMD ["status"]
    # kalau mau menjalankan mode lain, override:
    # command: ["gateway"]

volumes:
  nanobot-workspace:
